const ResourceStrings = {
    contact: 'Contact',
    contact_h1: 'We are here to bring diversity to tech.',
    contact_h3: 'To stay in touch for updates, please leave your email below.',
    contact_or: 'Or, contact us at ',
    hero_h1: 'We are Equitech.',
    hero_h2: 'What if every hackathon could be diverse?',
    hero_p1: 'Being dedicated to diversity while planning your hackathon can be difficult. At Equitech we acknowledge that and are dedicated to tackling the lack of diversity in tech by ensuring that your planning process is as seamless as possible, while keeping your most important metrics on the forefront.',
    hero_p2: 'Join us in our mission to make the tech industry as inclusive as possible',
    equitech_description_1: 'Being dedicated to diversity while planning your hackathon can be difficult. At Equitech we acknowledge that and are dedicated to tackling the lack of diversity in tech by ensuring that your planning process is as seamless as possible, while keeping your most important metrics on the forefront.',
    equitech_description_2: 'Join us in our mission to make the tech industry as inclusive as possible',
    equitech_email: 'contact@equitech.ca',
    equitech_footer: '(C) 2018 Equitech',
    equitech_logo_alt: 'Equitech Logo',
    img_1_alt: 'First picture describing ',
    img_top_alt: 'Second picture describing ',
    img_2_alt: 'Third picture describing ',
    projects: 'Projects',
    sign_up: 'Sign Up',
    starterhacks: 'StarterHacks',
    starterhacks_color: '#cc98c4',
    starterhacks_header: 'Introducing beginners to tech, regardless of career interests.',
    starterhacks_description: 'StarterHacks is Equitechs first initiative. It is an annual hackathon held at the University of Waterloo, and was where Equitech tested its concept, processes, and technology. StarterHacks focuses on inter-disciplinary collaboration while keeping an emphasis on learning.\n In both its runs so far, StarterHacks has achieved about 50% female participation, defying hackathon norms.',
    starterhacks_web: 'https://starterhacks.ca',
    tohacks: 'TOHacks',
    tohacks_header: 'Fostering an enviroment to embolden students towards a career in STEAM.',
    tohacks_color: '#616ab1',
    tohacks_description: 'We worked with TOHacks team to help plan and strategize their first hackathon. It is a 12-hour hackathon for high school and university students from the Toronto area and held at the University of Toronto. TOHacks focuses on bringing an inclusive and diverse group of students to put forth their innovative ideas for a day of problem-solving.',
    tohacks_web: 'https://tohacks.ca',
    visit: 'Visit Event Website'
};

export default ResourceStrings;
